'use strict';
(function () {
  var state, draft, page = 'clock', busy = false, auth=null, queue=Promise.resolve(), mediaUrls=[];
  var crypto=window.ReteCrypto;
  var titles = {clock:'General & speech',fonts:'Fonts & typography',pictures:'Pictures',sounds:'Sounds, bells & sun',timer:'Timer',timedate:'Time & date',layouts:'Layouts',experiments:'Experiments',files:'Import / Export',server:'Web server'};
  var structured = ['bells','timer_presets','layouts','layout_slides','sound_clips','markers','time_dst_custom','clock_padding'];
  var internal = ['sun_method_chosen','sun_twilight','calendar_week_monday','timer_alert','font','foreground'];
  var enumLabels = {screen_turn:['System','Follow sensor','Landscape','Portrait'],date_style:['Month name','Numeric','Day then month'],spoken_time_style:['As displayed','Numbers'],background_fit:['Stretch','Fit width','Fit height','Contain','Cover','Centre'],background_order_mode:['Name ascending','Name descending','Date ascending','Date descending','Custom','Random'],image_quality:['Kind to old phones','Better','Original'],clock_noon_style:['PM','AM','Noon','Zero'],clock_midnight_style:['AM','PM','24 hours','Midnight','Zero'],calendar_header:['Month','Month and year','Year and month'],calendar_week_start:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],time_source:['Phone time','Own UTC offset'],time_dst_preset:['None','Europe','North America','Southern hemisphere','Custom'],sun_high_rule:['No substitute','Middle of night','Seventh of night','Angle share','Nearest day']};
  function node(tag,text,cls){var e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
  function label(k){return k.replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();});}
  function message(text,error){var e=document.getElementById('message');e.textContent=text;e.className=error?'error':'';}
  function button(parent,text,fn){var b=node('button',text);b.type='button';b.onclick=function(){Promise.resolve().then(fn).catch(function(e){message(e.message,true);});};parent.appendChild(b);return b;}
  function input(parent,text,value,type,onchange,min,max){var l=node('label'),s=node('span',text),e=node('input');e.type=type||'text';if(type==='checkbox')e.checked=!!value;else e.value=value===undefined?'':value;if(min!==undefined)e.min=min;if(max!==undefined)e.max=max;e.onchange=function(){onchange(type==='checkbox'?e.checked:e.value);};l.appendChild(s);l.appendChild(e);parent.appendChild(l);return e;}
  function select(parent,text,value,values,onchange){var l=node('label'),e=node('select');l.appendChild(node('span',text));values.forEach(function(v){var o=node('option',typeof v==='object'?v.label:String(v));o.value=typeof v==='object'?v.value:String(v);e.appendChild(o);});e.value=String(value===undefined?'':value);if(e.selectedIndex<0){var o=node('option','Current: '+value);o.value=value;e.appendChild(o);e.value=value;}e.onchange=function(){onchange(e.value);};l.appendChild(e);parent.appendChild(l);return e;}
  function area(parent,text,value,change){var l=node('label',text),e=node('textarea');e.value=value||'';e.onchange=function(){change(e.value);};parent.appendChild(l);parent.appendChild(e);return e;}
  function card(parent,title){var c=node('section');c.appendChild(node('h3',title));parent.appendChild(c);return c;}
  function escapeRecord(v){return String(v).replace(/\\/g,'\\\\').replace(/\|/g,'\\|').replace(/\t/g,'\\t').replace(/\n/g,'\\n').replace(/\r/g,'\\r');}
  function splitRecord(s,sep){var rows=[],part='',escaped=false;for(var i=0;i<s.length;i++){var c=s[i];if(escaped){part+='\\'+c;escaped=false;}else if(c==='\\')escaped=true;else if(c===sep){rows.push(part);part='';}else part+=c;}if(escaped)part+='\\';rows.push(part);return rows;}
  function unescapeRecord(v){return v.replace(/\\(.)/g,function(_,c){return c==='n'?'\n':c==='r'?'\r':c==='t'?'\t':c;});}
  function soundChoices(){return [{value:'',label:'Built-in sound'}].concat(state.media.sounds.map(function(n){return {value:n,label:n};}));}
  function colour(n){return '#'+('000000'+((Number(n)>>>0)&0xffffff).toString(16)).slice(-6);}
  function colourNumber(v){return (parseInt(v.substring(1),16)|0xff000000)|0;}
  function showLogin(){layoutMemory={};if(auth)auth.key.fill(0);auth=null;state=null;draft=null;busy=false;mediaUrls.forEach(URL.revokeObjectURL);mediaUrls=[];document.getElementById('login').hidden=false;document.getElementById('logout').hidden=true;document.getElementById('reload').hidden=true;document.getElementById('connection').textContent='Signed out';document.getElementById('navigation').textContent='';document.getElementById('content').textContent='';document.getElementById('login-password').value='';}
  async function publicPost(path,values){var response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(values).toString(),credentials:'omit',redirect:'error'});if(!response.ok)throw new Error(await response.text());return response.json();}
  document.getElementById('login').onsubmit=async function(event){event.preventDefault();var password=document.getElementById('login-password').value,user=document.getElementById('login-user').value,submit=document.getElementById('sign-in');submit.disabled=true;try{crypto.checkPassword(password);var c=await publicPost('/auth/challenge',{user:user}),nonce=crypto.base64(crypto.random(24)),key=await crypto.derive(password,crypto.unbase64(c.salt),c.iterations);password='';document.getElementById('login-password').value='';var transcript=location.host+'\n'+c.id+'\n'+c.nonce+'\n'+nonce,proof=crypto.base64(await crypto.hmac(key,'reteclock-login-v1\n'+transcript));var result=await publicPost('/auth/login',{id:c.id,nonce:nonce,proof:proof});var signing=await crypto.hmac(key,'reteclock-session-v1\n'+transcript);key.fill(0);auth={id:result.id,key:signing,counter:0};document.getElementById('login').hidden=true;document.getElementById('logout').hidden=false;document.getElementById('reload').hidden=false;message('Signed in');await load();}catch(e){showLogin();message(e.message,true);}finally{submit.disabled=false;password='';}};
  function signedFetch(path,options){var current=auth;var next=queue.catch(function(){}).then(async function(){if(!current||auth!==current)throw new Error('Sign in first');options=Object.assign({},options||{});var headers=new Headers(options.headers||{}),counter=++current.counter,method=options.method||'GET';var hash=crypto.hex(await crypto.digest(options.body||'')),text=['reteclock-request-v1',current.id,String(counter),method,path,location.host,headers.get('Content-Type')||'',headers.get('X-CSRF-Token')||'',headers.get('X-Settings-Revision')||'',hash].join('\n');var body=options.body,size=body==null||body===''?0:(body instanceof Blob?body.size:new TextEncoder().encode(body).length);
      /* The head is proved by itself, length included: the clock stores no body for a head that is not. */
      var head=['reteclock-head-v1',current.id,String(counter),method,path,location.host,headers.get('Content-Type')||'',headers.get('X-CSRF-Token')||'',headers.get('X-Settings-Revision')||'',String(size)].join('\n');
      headers.set('X-Auth-Session',current.id);headers.set('X-Auth-Counter',String(counter));headers.set('X-Auth-Head',crypto.base64(await crypto.hmac(current.key,head)));headers.set('X-Auth-Proof',crypto.base64(await crypto.hmac(current.key,text)));options.headers=headers;options.credentials='omit';options.redirect='error';var response=await fetch(path,options);if(response.status===401){if(auth===current)showLogin();throw new Error('Session expired or request rejected. Sign in again.');}return response;});queue=next.then(function(){},function(){});return next;}
  async function request(path,options){var response=await signedFetch(path,options);var text=await response.text();if(!response.ok)throw new Error(response.status+': '+text);return text;}
  document.getElementById('logout').onclick=async function(){try{if(auth&&state)await post('/auth/logout',{});}catch(e){message(e.message,true);}finally{if(auth)auth.key.fill(0);showLogin();message('Signed out');}};
  async function load(){if(busy)return;var current=auth,next=JSON.parse(await request('/state'));if(!current||auth!==current)return;state=next;draft=Object.assign({},state.values);document.getElementById('connection').textContent=state.status;render();}
  async function post(path,values){var data=new URLSearchParams();Object.keys(values).forEach(function(k){data.append(k,String(values[k]));});return request(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':state.csrf},body:data.toString()});}
  async function save(){var values={revision:state.revision};Object.keys(draft).forEach(function(k){if(draft[k]!==state.values[k])values[k]=draft[k];});busy=true;try{message(await post('/settings',values));}finally{busy=false;}await load();}
  async function action(op,extra){var values=Object.assign({op:op,revision:state.revision},extra||{});message(await post('/action',values));await load();}
  function valueField(parent,f){var key=f.key,value=draft[key],set=function(v){draft[key]=String(v);};if(value===undefined)value=f.kind==='b'?'false':f.kind==='i'?String(f.min<0?0:f.min):'';
    if(key.indexOf('font_')===0)return select(parent,label(key),value,[{value:'',label:'System font'}].concat(state.media.fonts.map(function(n){return {value:n,label:n};})),set);
    if(key==='tts_engine')return select(parent,'Speech engine',value,[{value:'',label:'Phone default'}].concat(state.engines),function(v){set(v);draft.tts_language='';render();});
    if(key==='tts_language')return select(parent,'Speech language',value,[{value:'',label:'Phone default'}].concat(state.voices.filter(function(v){return v.engine===(draft.tts_engine||state.defaultEngine);}).map(function(v){return {value:v.value,label:v.label};})),set);
    if(key==='calendar_system')return select(parent,'Calendar',value,state.calendars.map(function(n,i){return {value:i,label:n};}),set);
    if(key==='sun_method')return select(parent,'Published astronomical method',value,state.methods.map(function(n,i){return {value:i,label:n};}),set);
    if(key==='text_color'||key==='background_color')return input(parent,label(key),colour(value),'color',function(v){set(colourNumber(v));});
    if(key==='pool_background'||key==='pool_text'||key==='background_order'){area(parent,label(key)+' (one stored picture per line)',value,set);return;}
    if(/^(names_|spoken_months_|spoken_weekdays_)/.test(key)){var names=value?value.split('\t'):[],count=key.indexOf('weekdays')>=0?7:13;var d=node('details');d.appendChild(node('summary',label(key)+' · '+state.calendars[Number(key.match(/\d+$/)[0]) ]));parent.appendChild(d);for(var i=0;i<count;i++)(function(at){input(d,String(at+1),names[at]||'','text',function(v){names[at]=v;set(names.join('\t'));});})(i);return;}
    if(f.kind==='b')return input(parent,label(key),value==='true','checkbox',set);
    if(f.choices)return select(parent,label(key),value,f.choices.map(function(v){return {value:v,label:key==='sleep_brightness'?(v==='-1'?'Use system brightness':v+' %'):v};}),set);
    if(enumLabels[key])return select(parent,label(key),value,enumLabels[key].map(function(v,i){return {value:i,label:v};}).filter(function(v){return key!=='image_quality'||v.value<=state.qualityMax;}),set);
    if(f.kind==='i'){var max=key==='image_quality'?state.qualityMax:f.max;return input(parent,label(key),value,'number',set,f.min,max);}
    if(value.indexOf('\n')>=0||key==='spoken_template')return area(parent,label(key),value,set);
    input(parent,label(key),value,'text',set);
  }
  function listActions(parent,rows,i,write,renderRows){var box=node('div',undefined,'actions');parent.appendChild(box);button(box,'Move up',function(){if(i>0){var a=rows.splice(i,1)[0];rows.splice(i-1,0,a);write();renderRows();}});button(box,'Move down',function(){if(i<rows.length-1){var a=rows.splice(i,1)[0];rows.splice(i+1,0,a);write();renderRows();}});button(box,'Delete',function(){rows.splice(i,1);write();renderRows();});}
  function bells(parent){var rows=(draft.bells||'').split('\n').filter(Boolean).map(function(l){var a=splitRecord(l,'|');return {on:a[0]==='1',days:Number(a[1]),minute:Number(a[2]),sound:unescapeRecord(a[3]),name:unescapeRecord(a[4]||''),repeats:Number(a[5]||1),snooze:Number(a[6]||0),wake:a[7]==='1',event:Number(a[8]||0),offset:Number(a[9]||0)};});var c=card(parent,'Bells and alarms'),list=node('div');c.appendChild(list);
    function write(){draft.bells=rows.map(function(r){var a=[r.on?1:0,r.days,r.minute,escapeRecord(r.sound),escapeRecord(r.name),r.repeats,r.snooze];if(r.wake||r.event)a.push(r.wake?1:0);if(r.event)a.push(r.event,r.offset);return a.join('|');}).join('\n');}
    function draw(){list.replaceChildren();rows.forEach(function(r,i){var box=card(list,'Bell '+(i+1));input(box,'Enabled',r.on,'checkbox',function(v){r.on=v;write();});input(box,'Label',r.name,'text',function(v){r.name=v;write();});var time=input(box,'Time',('0'+Math.floor(r.minute/60)).slice(-2)+':'+('0'+r.minute%60).slice(-2),'time',function(v){var p=v.split(':');r.minute=Number(p[0])*60+Number(p[1]);write();});time.step=60;
      var days=node('div',undefined,'days');box.appendChild(days);['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(function(n,d){input(days,n,!!(r.days&(1<<d)),'checkbox',function(v){r.days=v?r.days|(1<<d):r.days&~(1<<d);write();});});
      select(box,'Sound',r.sound,soundChoices(),function(v){r.sound=v;write();});input(box,'Repeats',r.repeats,'number',function(v){r.repeats=Number(v);write();},1,10);input(box,'Put off (minutes; 0 disables)',r.snooze,'number',function(v){r.snooze=Number(v);write();},0,30);input(box,'Wake the phone (requires alarm experiment)',r.wake,'checkbox',function(v){r.wake=v;write();});select(box,'Time or astronomical event',r.event,['At set time','Sunrise','Sunset','Solar noon','Dawn','Dusk','Night middle','Afternoon shadow','Evening'].map(function(n,i){return {value:i,label:n};}),function(v){r.event=Number(v);write();});input(box,'Event offset (minutes)',r.offset,'number',function(v){r.offset=Number(v);write();},-180,180);listActions(box,rows,i,write,draw);});}
    button(c,'Add bell',function(){rows.push({on:true,days:127,minute:420,sound:'',name:'',repeats:1,snooze:0,wake:false,event:0,offset:0});write();draw();});draw();}
  function clips(parent){var rows=(draft.sound_clips||'').split('\n').filter(Boolean).map(function(l){var a=splitRecord(l,'|');return {name:unescapeRecord(a[0]),start:Number(a[1]),end:Number(a[2]),loops:a[3]==='1'};});var c=card(parent,'Sound clip start/end and repeat'),list=node('div');c.appendChild(list);function write(){draft.sound_clips=rows.map(function(r){return [escapeRecord(r.name),r.start,r.end,r.loops?1:0].join('|');}).join('\n');}function draw(){list.replaceChildren();rows.forEach(function(r,i){var b=card(list,r.name);select(b,'Stored sound',r.name,state.media.sounds,function(v){r.name=v;write();});input(b,'Start (tenths of a second)',r.start,'number',function(v){r.start=Number(v);write();},0,36000);input(b,'End (tenths; 0 means whole end)',r.end,'number',function(v){r.end=Number(v);write();},0,36000);input(b,'Repeat',r.loops,'checkbox',function(v){r.loops=v;write();});listActions(b,rows,i,write,draw);});}button(c,'Adjust a sound',function(){if(!state.media.sounds.length)throw new Error('Upload a sound first');rows.push({name:state.media.sounds[0],start:0,end:0,loops:false});write();draw();});draw();}
  function timers(parent){var rows=(draft.timer_presets||'').split('\n').filter(Boolean).map(function(l){var a=splitRecord(l,'\t'),h=splitRecord(a.shift(),'|');return {name:unescapeRecord(h[0]),loops:h[1]==='1',start:unescapeRecord(h[2]||''),finish:unescapeRecord(h[3]||''),intervals:a.map(function(p){var x=splitRecord(p,'|');return {name:unescapeRecord(x[0]),ms:Number(x[1]),colour:Number(x[2]),endColour:Number(x[3]),message:unescapeRecord(x[4]),pre:Number(x[5]),start:unescapeRecord(x[6]||''),warning:unescapeRecord(x[7]||'')};})};});var c=card(parent,'Timer presets and intervals'),list=node('div');c.appendChild(list);function write(){draft.timer_presets=rows.map(function(r){return [escapeRecord(r.name),r.loops?1:0,escapeRecord(r.start),escapeRecord(r.finish)].join('|')+r.intervals.map(function(x){return '\t'+[escapeRecord(x.name),x.ms,x.colour,x.endColour,escapeRecord(x.message),x.pre,escapeRecord(x.start),escapeRecord(x.warning)].join('|');}).join('');}).join('\n');}
    function interval(){return {name:'Interval',ms:60000,colour:-11684180,endColour:-1092784,message:'',pre:0,start:'',warning:''};}
    function draw(){list.replaceChildren();rows.forEach(function(r,i){var b=card(list,'Preset '+(i+1));input(b,'Name',r.name,'text',function(v){r.name=v;write();});input(b,'Repeat preset',r.loops,'checkbox',function(v){r.loops=v;write();});select(b,'Start sound',r.start,soundChoices(),function(v){r.start=v;write();});select(b,'Finish sound',r.finish,soundChoices(),function(v){r.finish=v;write();});r.intervals.forEach(function(x,j){var d=card(b,'Interval '+(j+1));input(d,'Name',x.name,'text',function(v){x.name=v;write();});input(d,'Duration (seconds)',x.ms/1000,'number',function(v){x.ms=Math.round(Number(v)*1000);write();},1,7861957671667);input(d,'Start colour',colour(x.colour),'color',function(v){x.colour=colourNumber(v);write();});input(d,'End colour',colour(x.endColour),'color',function(v){x.endColour=colourNumber(v);write();});input(d,'Spoken message',x.message,'text',function(v){x.message=v;write();});input(d,'Pre-alarm (seconds)',x.pre,'number',function(v){x.pre=Number(v);write();},0,3600);select(d,'Interval start sound',x.start,soundChoices(),function(v){x.start=v;write();});select(d,'Pre-alarm sound',x.warning,soundChoices(),function(v){x.warning=v;write();});listActions(d,r.intervals,j,write,draw);});button(b,'Add interval',function(){r.intervals.push(interval());write();draw();});listActions(b,rows,i,write,draw);});}
    button(c,'Add preset',function(){rows.push({name:'Timer',loops:false,start:'',finish:'',intervals:[interval()]});write();draw();});draw();}
  function parseLayouts(){var text=draft.layouts||'',pieces=text.split(/^--$/m),head=pieces.shift(),chosen=(head.match(/chosen=(\d+),(\d+)/)||['',0,0]).slice(1).map(Number);var presets=pieces.map(function(s){var p={name:'layout',way:'portrait',boxes:[],background:[],text:[]};s.split('\n').forEach(function(l){var at=l.indexOf('='),k=l.slice(0,at),v=l.slice(at+1);if(k==='name')p.name=unescapeRecord(v);if(k==='way')p.way=v;if(k==='box')p.boxes.push(v.split('|'));if(k==='picture'){var a=v.split('|');if(p[a[0]])p[a[0]].push(unescapeRecord(a[1]));}});var sources=JSON.parse(draft.layout_sources||'[]'),old=sources.find(function(a){return a.name===p.name&&a.landscape===(p.way==='landscape');});p.source=old?old.source:p.name;p.sourceWay=old?(old.sourceLandscape?'landscape':'portrait'):p.way;return p;});return {chosen:chosen,presets:presets};}
  // ---- The layout canvas (R142) ----------------------------------------------------------------
  // The clock's own screen to scale, with the layout's boxes on it, as the editor on the device has
  // it: a corner resizes, the inside moves, a strip let go of takes the edge it is nearest, and Undo
  // takes the last change back. The arithmetic is the core's — Anchor, Grab, Strips.nearest and
  // LayoutBox.placedOnEdge — said again here, because the page has no other way to it.
  var fieldNames={hour_minute:'Time',hour:'Hour',minute:'Minute',meridiem:'AM / PM',second:'Seconds',weekday:'Weekday',month_day:'Month and day',year:'Year',weekday_date:'Weekday and date',small_line:'The small line',quote:'Saying',calendar_title:'Calendar title',calendar_weekday:'Calendar weekdays',calendar_day:'Calendar days',calendar:'Month grid',timer:'Timer strip',gap:'Gap'};
  var anchorNames=['Top left','Top centre','Top right','Middle left','Middle centre','Middle right','Bottom left','Bottom centre','Bottom right'];
  // What the editor takes a box to be on an axis it leaves to the field: BoxPlan.DEFAULT_HEIGHT_SHARE, and the device editor's two fifths across.
  var NATURAL_WIDTH=0.4,NATURAL_HEIGHT=0.12,layoutMemory={},showBackdrop=true;
  function fieldName(f){return fieldNames[f]||label(f);}
  function screenOf(way){var a=Number(state.width)||720,b=Number(state.height)||1280,low=Math.min(a,b),high=Math.max(a,b);return way==='landscape'?{w:high,h:low}:{w:low,h:high};}
  // One measurement of a box line: whole thousandths of the screen, or the fraction the first version wrote.
  function measure(v,fallback){if(v===undefined||v===null||String(v).trim()==='')return fallback;var t=String(v).trim(),n=/[.eE]/.test(t)?parseFloat(t):parseInt(t,10)/1000;return isNaN(n)?fallback:n;}
  function steps(f){return String(Math.max(-1000,Math.min(1000,Math.round(f*1000))));}
  function sizeSteps(f){return String(Math.max(1,Math.min(1000,Math.round(f*1000))));}
  function boxAnchor(x){var a=parseInt(x[1],10);return a>=0&&a<=8?a:4;}
  function boxEdge(x){var e=parseInt(x[9],10);return e>=0&&e<=3?e:-1;}
  function takesAnEdge(x){return x[0]==='timer'||x[0]==='quote';}
  function along(side,offset,size,extent){return side===0?offset:side===2?extent-size-offset:(extent-size)/2+offset;}
  function offsetOf(side,near,size,extent){return side===0?near:side===2?extent-size-near:near-(extent-size)/2;}
  // Where a box is on the screen, in the screen's own pixels: left, top, width, height.
  function boxRect(x,s){var a=boxAnchor(x),w=measure(x[4],-1),h=measure(x[5],-1);w=w>0?Math.min(1,w)*s.w:s.w*NATURAL_WIDTH;h=h>0?Math.min(1,h)*s.h:s.h*NATURAL_HEIGHT;return [along(a%3,measure(x[2],0)*s.w,w,s.w),along(Math.floor(a/3),measure(x[3],0)*s.h,h,s.h),w,h];}
  // The same box sitting at this rectangle, keeping the anchor it had: a drag is not a change of mind about what a box is measured from.
  function boxOffsets(x,r,s){var a=boxAnchor(x);x[2]=steps(offsetOf(a%3,r[0],r[2],s.w)/s.w);x[3]=steps(offsetOf(Math.floor(a/3),r[1],r[3],s.h)/s.h);}
  function boxPlace(x,r,s){boxOffsets(x,r,s);x[4]=sizeSteps(r[2]/s.w);x[5]=sizeSteps(r[3]/s.h);}
  // Grab.at: 0 the inside, 1–4 the corners (top left, top right, bottom left, bottom right), -1 nothing. A handle may not eat more than a third of the box.
  function grabAt(r,x,y,reach){var left=r[0],top=r[1],right=r[0]+r[2],bottom=r[1]+r[3],grip=Math.min(reach,Math.min(r[2],r[3])/3);function near(v,t){return v>=t-grip&&v<=t+grip;}
    if(near(x,left)&&near(y,top))return 1;if(near(x,right)&&near(y,top))return 2;if(near(x,left)&&near(y,bottom))return 3;if(near(x,right)&&near(y,bottom))return 4;return x>=left&&x<=right&&y>=top&&y<=bottom?0:-1;}
  // Grab.apply: a box cannot be turned inside out, and nothing leaves the screen.
  function grabApply(r,grabbed,dx,dy,s,least){function clamp(v,low,high){return high<low?low:v<low?low:v>high?high:v;}
    if(grabbed===0)return [clamp(r[0]+dx,0,s.w-r[2]),clamp(r[1]+dy,0,s.h-r[3]),r[2],r[3]];
    var left=r[0],top=r[1],right=r[0]+r[2],bottom=r[1]+r[3];
    if(grabbed===1||grabbed===3)left=clamp(left+dx,0,right-least);else right=clamp(right+dx,left+least,s.w);
    if(grabbed===1||grabbed===2)top=clamp(top+dy,0,bottom-least);else bottom=clamp(bottom+dy,top+least,s.h);
    return [left,top,right-left,bottom-top];}
  // Strips.nearest: the edge the middle of the box is closest to; the saying takes only the head and the foot.
  function nearestEdge(r,s,sides){var cx=r[0]+r[2]/2,cy=r[1]+r[3]/2,best=0,distance=cy/s.h;if((s.h-cy)/s.h<distance){best=1;distance=(s.h-cy)/s.h;}if(sides){if(cx/s.w<distance){best=2;distance=cx/s.w;}if((s.w-cx)/s.w<distance)best=3;}return best;}
  // LayoutBox.placedOnEdge: the whole of that edge, at the thickness the box already had.
  function layOnEdge(x,edge,s){if(!(edge>=0&&edge<=3)){x[9]='-1';return;}var was=boxEdge(x),side=was===2||was===3,w=measure(x[4],-1),h=measure(x[5],-1),thickness=side?(w>0?w*s.w:s.w*NATURAL_HEIGHT):(h>0?h*s.h:s.h*NATURAL_HEIGHT);
    x[2]='0';x[3]='0';if(edge<2){x[1]=edge===0?'1':'7';x[4]='1000';x[5]=sizeSteps(thickness/s.h);}else{x[1]=edge===2?'3':'5';x[4]=sizeSteps(thickness/s.w);x[5]='1000';}x[9]=String(edge);}
  function completeBox(x){var blank=['','4','0','0','-1','-1','4','0','1','-1'];for(var k=1;k<10;k++)if(x[k]===undefined||x[k]==='')x[k]=blank[k];return x;}
  function builtinBoxes(way){var lines=state.builtin&&state.builtin[way];return lines&&lines.length?lines.map(function(l){return completeBox(l.split('|'));}):null;}
  function perCent(v){var f=measure(v,-1);return f<0&&v!==undefined&&parseInt(v,10)===-1?'':(Math.round(f*1000)/10).toFixed(1);}
  function fromPerCent(typed,fallback){var t=String(typed).trim().replace(',','.').replace('%','');if(t==='')return fallback;var n=parseFloat(t);return isNaN(n)?fallback:n/100;}

  function layoutEditor(parent,p,write){
    var s=screenOf(p.way),canvas=node('canvas'),width=p.way==='landscape'?640:360;if(width*s.h/s.w>560)width=Math.round(560*s.w/s.h);
    canvas.width=width;canvas.height=Math.round(width*s.h/s.w);canvas.setAttribute('aria-label','Layout '+p.name+', '+p.way);
    parent.appendChild(node('p','Drag a box to move it and a corner to resize it; the numbers of the box you last touched are underneath. A timer strip or a saying strip takes the edge you drop it nearest.','hint'));
    // Side by side where there is room: the numbers change under the hand that drags.
    var frame=node('div',undefined,'editor'),side=node('div',undefined,'numbers');parent.appendChild(frame);frame.appendChild(canvas);frame.appendChild(side);
    var tools=node('div',undefined,'actions'),panel=node('div'),said=node('p','','hint');side.appendChild(tools);side.appendChild(said);side.appendChild(panel);
    // What the clock thinks of the arrangement, in words, while it can still be changed: whether writing fits is a matter of the clock's fonts, so the clock is asked (R143). The latest question is the one answered.
    var asked=0,waiting=null;
    function judge(){if(waiting)clearTimeout(waiting);waiting=setTimeout(function(){waiting=null;var mine=++asked,current=auth;if(!current||!said.isConnected)return;
      post('/layout-check',{way:p.way,boxes:p.boxes.map(function(b){return b.join('|');}).join('\n')}).then(function(text){if(mine!==asked||auth!==current)return;
        var lines=text.split('\n').filter(Boolean).map(function(l){var a=l.split('|'),f=fieldName(a[1]);return a[0]==='3'?'Nothing would be drawn: every box is hidden.':a[0]==='1'?f+' is partly off the screen.':a[0]==='2'?f+' overlaps '+fieldName(a[2])+'.':f+' is too small for what it can show — the writing shrinks to '+a[3]+'%.';});
        said.className=lines.length?'hint warning':'hint';said.textContent=lines.length?lines.join('\n'):'Nothing in the way.';}).catch(function(){if(mine===asked){said.className='hint';said.textContent='The clock could not be asked about this arrangement.';}});},350);}
    // What was chosen and what can be undone outlive a save: the page is drawn afresh from the clock's answer each time.
    var m=layoutMemory[p.way+'/'+p.name]||(layoutMemory[p.way+'/'+p.name]={sel:-1,undo:[]});if(m.sel>=p.boxes.length)m.sel=-1;
    var grabbed=-1,last=null,moved=false;
    function remember(){m.undo.push(JSON.stringify(p.boxes));if(m.undo.length>60)m.undo.shift();}
    function selected(){return m.sel>=0&&m.sel<p.boxes.length?p.boxes[m.sel]:null;}
    function changed(){write();paint();numbers();judge();}
    function paint(){var c=canvas.getContext('2d'),k=canvas.width/s.w;c.fillStyle='#000';c.fillRect(0,0,canvas.width,canvas.height);
      // The background, placed as the clock places it (ImageFit) and veiled by a third of black: the boxes are thin outlines, and a photograph is not obliged to be dark enough to read them against.
      if(showBackdrop&&m.picture){var iw=m.picture.naturalWidth,ih=m.picture.naturalHeight,tw=canvas.width/iw,th=canvas.height/ih,mode=Number(draft.background_fit===undefined?4:draft.background_fit),sx=mode===0?tw:mode===1?tw:mode===2?th:mode===3?Math.min(tw,th):mode===5?1:Math.max(tw,th),sy=mode===0?th:sx;
        if(iw>0&&ih>0){c.drawImage(m.picture,(canvas.width-iw*sx)/2,(canvas.height-ih*sy)/2,iw*sx,ih*sy);c.fillStyle='rgba(0,0,0,.333)';c.fillRect(0,0,canvas.width,canvas.height);}}
      p.boxes.forEach(function(x,j){var r=boxRect(x,s),shown=x[8]!=='0',chosen=j===m.sel,left=r[0]*k,top=r[1]*k,w=r[2]*k,h=r[3]*k;
        c.lineWidth=chosen?2:1;c.strokeStyle=!shown?'#555':chosen?'#4db6ac':'#8a8a8a';c.strokeRect(left+.5,top+.5,Math.max(1,w-1),Math.max(1,h-1));
        c.fillStyle=shown?'#f2f2f2':'#666';c.font=Math.max(9,Math.min(13,h*.5))+'px system-ui,sans-serif';c.fillText(fieldName(x[0])+(x[7]==='1'?' (locked)':''),left+3,top+h-3,Math.max(10,w-6));
        if(chosen&&shown&&x[7]!=='1'){c.fillStyle='#4db6ac';[[left,top],[left+w,top],[left,top+h],[left+w,top+h]].forEach(function(q){c.fillRect(q[0]-4,q[1]-4,8,8);});}});}
    function point(e){var r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*s.w,y:(e.clientY-r.top)/r.height*s.h,reach:14/r.width*s.w};}
    canvas.onpointerdown=function(e){var at=point(e);m.sel=-1;grabbed=-1;
      // The box on top wins, as in every drawing program; a locked one is chosen and stays put.
      for(var j=p.boxes.length-1;j>=0;j--){var what=grabAt(boxRect(p.boxes[j],s),at.x,at.y,at.reach);if(what>=0){m.sel=j;grabbed=p.boxes[j][7]==='1'?-1:what;break;}}
      last=at;moved=false;try{canvas.setPointerCapture(e.pointerId);}catch(ignored){}paint();numbers();};
    canvas.onpointermove=function(e){var x=selected();if(!x||grabbed<0||!last)return;var at=point(e),dx=at.x-last.x,dy=at.y-last.y;if(!dx&&!dy)return;
      if(!moved){remember();moved=true;}boxPlace(x,grabApply(boxRect(x,s),grabbed,dx,dy,s,Math.min(s.w,s.h)*.02),s);last=at;write();paint();};
    canvas.onpointerup=canvas.onpointercancel=function(){var x=selected();
      if(moved&&x&&boxEdge(x)>=0){layOnEdge(x,nearestEdge(boxRect(x,s),s,x[0]!=='quote'),s);write();}
      if(moved)judge();grabbed=-1;last=null;moved=false;paint();numbers();};
    function numbers(){panel.replaceChildren();
      if(p.boxes.length)select(panel,'Selected field',m.sel,[{value:-1,label:'None'}].concat(p.boxes.map(function(x,j){return {value:j,label:(j+1)+' · '+fieldName(x[0])};})),function(v){m.sel=Number(v);paint();numbers();});
      var x=selected();if(!x)return;
      function edit(fn){return function(v){remember();fn(v);changed();};}
      select(panel,'Field',x[0],state.boxFields.map(function(f){return {value:f,label:fieldName(f)};}),edit(function(v){x[0]=v;if(!takesAnEdge(x))x[9]='-1';}));
      // Another anchor is another way of saying where the box is, not another place: the offsets are worked out again for it.
      select(panel,'Measured from',boxAnchor(x),anchorNames.map(function(n,k){return {value:k,label:n};}),edit(function(v){var r=boxRect(x,s);x[1]=v;boxOffsets(x,r,s);}));
      input(panel,'X %',perCent(x[2]),'text',edit(function(v){x[2]=steps(fromPerCent(v,0));}));
      input(panel,'Y %',perCent(x[3]),'text',edit(function(v){x[3]=steps(fromPerCent(v,0));}));
      input(panel,'Width %',perCent(x[4]),'text',edit(function(v){var f=fromPerCent(v,-1);x[4]=f>0?sizeSteps(f):'-1';})).placeholder='as the field asks';
      input(panel,'Height %',perCent(x[5]),'text',edit(function(v){var f=fromPerCent(v,-1);x[5]=f>0?sizeSteps(f):'-1';})).placeholder='as the field asks';
      select(panel,'Writing sits inside the box',x[6]===undefined?4:x[6],anchorNames.map(function(n,k){return {value:k,label:n};}),edit(function(v){x[6]=v;}));
      input(panel,'Shown',x[8]!=='0','checkbox',edit(function(v){x[8]=v?'1':'0';}));
      input(panel,'Locked',x[7]==='1','checkbox',edit(function(v){x[7]=v?'1':'0';}));
      if(takesAnEdge(x))select(panel,'Takes a whole edge',boxEdge(x),[{value:-1,label:'No, an ordinary box'},{value:0,label:'Top'},{value:1,label:'Bottom'}].concat(x[0]==='quote'?[]:[{value:2,label:'Left'},{value:3,label:'Right'}]),edit(function(v){layOnEdge(x,Number(v),s);}));
      var order=node('div',undefined,'actions');panel.appendChild(order);
      // The last in the list is in front, and is what a touch finds first.
      button(order,'Bring to front',function(){remember();p.boxes.push(p.boxes.splice(m.sel,1)[0]);m.sel=p.boxes.length-1;changed();});
      button(order,'Send to back',function(){remember();p.boxes.unshift(p.boxes.splice(m.sel,1)[0]);m.sel=0;changed();});}
    button(tools,'Add field',function(){remember();p.boxes.push(['hour_minute','4','0','0','800','200','4','0','1','-1']);m.sel=p.boxes.length-1;changed();});
    button(tools,'Remove selected',function(){if(!selected()){message('Choose a field on the layout first, then Remove.',true);return;}remember();var gone=p.boxes.splice(m.sel,1)[0];m.sel=-1;changed();message(fieldName(gone[0])+' taken off. Undo puts it back.');});
    button(tools,'Undo',function(){if(!m.undo.length)return;p.boxes=JSON.parse(m.undo.pop());if(m.sel>=p.boxes.length)m.sel=-1;changed();});
    if(builtinBoxes(p.way))button(tools,'Start from the automatic arrangement',function(){remember();p.boxes=builtinBoxes(p.way);m.sel=-1;changed();});
    input(side,'Show the background',showBackdrop,'checkbox',function(v){showBackdrop=v;paint();});
    // This layout's own picture if it carries one, or else the first of the shared pool: the clock decides which, as for its own editor.
    if(m.picture===undefined){m.picture=null;var current=auth;signedFetch('/media?kind=backdrop&layout='+encodeURIComponent(p.name)+'&way='+p.way).then(async function(r){if(!r.ok)return;var url=URL.createObjectURL(await r.blob()),img=new Image();img.onload=function(){URL.revokeObjectURL(url);if(auth===current&&layoutMemory[p.way+'/'+p.name]===m){m.picture=img;paint();}};img.onerror=function(){URL.revokeObjectURL(url);};img.src=url;}).catch(function(){});}
    paint();numbers();judge();}

  function layouts(parent){var book=parseLayouts(),c=card(parent,'Portrait and landscape layouts'),list=node('div');c.appendChild(list);
    // A strip is shown where the clock draws it: along its edge, wherever its box was left (issue #68).
    book.presets.forEach(function(p){var s=screenOf(p.way);p.boxes.forEach(function(x){completeBox(x);if(boxEdge(x)>=0)layOnEdge(x,boxEdge(x),s);});});
    function write(){draft.layout_sources=JSON.stringify(book.presets.map(function(p){return {name:p.name,landscape:p.way==='landscape',source:p.source||'',sourceLandscape:p.sourceWay==='landscape'};}));draft.layouts='chosen='+book.chosen.join(',')+'\n'+book.presets.map(function(p){return '--\nname='+escapeRecord(p.name)+'\nway='+p.way+'\n'+p.boxes.map(function(b){return 'box='+b.join('|')+'\n';}).join('')+['background','text'].map(function(role){return p[role].map(function(n){return 'picture='+role+'|'+escapeRecord(n)+'\n';}).join('');}).join('');}).join('');}
    function draw(){list.replaceChildren();['portrait','landscape'].forEach(function(way,idx){select(list,'Active '+way+' layout',book.chosen[idx],[{value:0,label:'Automatic'}].concat(book.presets.filter(function(p){return p.way===way;}).map(function(p,i){return {value:i+1,label:p.name};})),function(v){book.chosen[idx]=Number(v);write();});});
      book.presets.forEach(function(p,i){var b=card(list,p.name+' · '+p.way);input(b,'Name (letters, digits, underscore)',p.name,'text',function(v){p.name=v;write();});select(b,'Orientation',p.way,['portrait','landscape'],function(v){p.way=v;book.chosen=[0,0];write();draw();});
        layoutEditor(b,p,write);
        area(b,'Background pictures (from this theme; one per line)',p.background.join('\n'),function(v){p.background=v.split('\n').filter(Boolean);write();});area(b,'Text pictures (from this theme; one per line)',p.text.join('\n'),function(v){p.text=v.split('\n').filter(Boolean);write();});
        var end=node('div',undefined,'actions');b.appendChild(end);
        button(end,'Duplicate layout',function(){book.presets.push({name:p.name+'Copy',way:p.way,boxes:JSON.parse(JSON.stringify(p.boxes)),background:p.background.slice(),text:p.text.slice(),source:p.source,sourceWay:p.sourceWay});write();draw();});button(end,'Delete layout',function(){book.presets.splice(i,1);book.chosen=[0,0];write();draw();});});}
    button(c,'New layout',function(){book.presets.push({name:'layout'+(book.presets.length+1),way:'portrait',boxes:builtinBoxes('portrait')||[['hour_minute','4','0','0','800','200','4','0','1','-1']],background:[],text:[]});write();draw();});draw();slides(parent,book);}
  function slides(parent,book){var rows=[],on=[false,false],anchor='0';(draft.layout_slides||'').split('\n').forEach(function(l){if(l.indexOf('on=')===0)on=l.slice(3).split(',').map(function(v){return v==='1';});else if(l.indexOf('anchor=')===0)anchor=l.slice(7);else if(/^[PL]\|/.test(l)){var a=l.split('|');rows.push({way:a[0],seconds:Number(a[1]),background:a[2]==='1',layout:a[3]});}});var c=card(parent,'Layouts in turn'),list=node('div');c.appendChild(list);function write(){draft.layout_slides='on='+on.map(function(v){return v?1:0;}).join(',')+'\nanchor='+anchor+'\n'+rows.map(function(r){return [r.way,r.seconds,r.background?1:0,r.layout].join('|');}).join('\n')+(rows.length?'\n':'');}function draw(){list.replaceChildren();input(list,'Portrait slides',on[0],'checkbox',function(v){on[0]=v;write();});input(list,'Landscape slides',on[1],'checkbox',function(v){on[1]=v;write();});rows.forEach(function(r,i){var b=card(list,'Slide '+(i+1));select(b,'Orientation',r.way,[{value:'P',label:'Portrait'},{value:'L',label:'Landscape'}],function(v){r.way=v;r.layout='Automatic';write();draw();});select(b,'Layout',r.layout,['Automatic'].concat(book.presets.filter(function(p){return p.way===(r.way==='P'?'portrait':'landscape');}).map(function(p){return p.name;})),function(v){r.layout=v;write();});input(b,'Duration (seconds)',r.seconds,'number',function(v){r.seconds=Number(v);write();},10,86400);input(b,'Background',r.background,'checkbox',function(v){r.background=v;write();});listActions(b,rows,i,write,draw);});}button(c,'Add slide',function(){rows.push({way:'P',seconds:300,background:true,layout:'Automatic'});write();draw();});draw();}
  function smallStructures(parent){var c=card(parent,'12-hour markers');var m=(draft.markers||'').split('\t');['AM','PM','Noon','Midnight'].forEach(function(n,i){input(c,n,m[i]||'','text',function(v){m[i]=v;draft.markers=m.join('\t');});});var pad=card(parent,'Leading zeros'),bits=Number(draft.clock_padding||0);['24-hour hour','12-hour hour','Minute','Second','Month','Numeric day','Named day'].forEach(function(n,i){input(pad,n,!!(bits&(1<<i)),'checkbox',function(v){bits=v?bits|(1<<i):bits&~(1<<i);draft.clock_padding=String(bits);});});}
  function dst(parent){var c=card(parent,'Custom summer time rule'),a=(draft.time_dst_custom||'3,0,0,60,10,0,0,60,60').split(',');['Start month','Start weekday (Sunday 0)','Start occurrence (last 0)','Start minute','End month','End weekday','End occurrence','End minute','Advance minutes'].forEach(function(n,i){input(c,n,a[i],'number',function(v){a[i]=v;draft.time_dst_custom=a.join(',');});});}
  function media(parent,kind){var c=card(parent,label(kind)+' library'),list=node('div');c.appendChild(list);state.media[kind].forEach(function(n){var b=node('div',undefined,'card');b.appendChild(node('strong',n));list.appendChild(b);if(kind==='pictures'){var img=node('img');img.className='preview';img.alt=n;b.appendChild(img);var current=auth;signedFetch('/media?kind=pictures&name='+encodeURIComponent(n)).then(async function(r){if(!r.ok)throw new Error('Picture unavailable');var blob=await r.blob();if(auth===current&&img.isConnected){var url=URL.createObjectURL(blob);mediaUrls.push(url);img.src=url;}}).catch(function(e){if(auth===current)message(e.message,true);});}var actions=node('div',undefined,'actions');b.appendChild(actions);if(kind==='sounds')button(actions,'Test on device',function(){return action('test-sound',{name:n});});button(actions,'Rename',function(){var next=prompt('New name',n);if(next)return action('rename',{kind:kind,name:n,newName:next});});button(actions,'Delete',function(){if(confirm('Delete '+n+' from the clock?'))return action('delete',{kind:kind,name:n});});});upload(c,kind);}
  function upload(parent,kind){var file=node('input');file.type='file';parent.appendChild(file);button(parent,'Validate upload',async function(){if(!file.files.length)throw new Error('Choose a file');await sendFile(file.files[0],kind,'preview');});button(parent,'Import upload',async function(){if(!file.files.length)throw new Error('Choose a file');if(confirm('Import to the clock? A settings import stops a running timer.')){await sendFile(file.files[0],kind,'apply');await load();}});}
  async function sendFile(file,kind,mode){if(file.size>64*1024*1024)throw new Error('Maximum upload: 64 MiB');var query=new URLSearchParams({kind:kind||'settings',name:file.name,mode:mode});var sections=document.querySelectorAll('[data-section]:checked');if(page==='files'){query.set('sections',Array.from(sections).map(function(e){return e.dataset.section;}).join(','));['fonts','pictures','sounds'].forEach(function(k){query.set(k,String(document.getElementById('carry-'+k).checked));});}busy=true;try{message(await request('/upload?'+query.toString(),{method:'POST',headers:{'Content-Type':'application/octet-stream','X-CSRF-Token':state.csrf,'X-Settings-Revision':String(state.revision)},body:file}));}finally{busy=false;}}
  function files(parent){var c=card(parent,'Choose settings and files');['clock','fonts','pictures','sounds','timer','timedate'].forEach(function(s){var e=input(c,titles[s],true,'checkbox',function(){});e.dataset.section=s;});['fonts','pictures','sounds'].forEach(function(s){var e=input(c,'Include '+s+' files',true,'checkbox',function(){});e.id='carry-'+s;});var box=card(parent,'Upload INI/text, settings ZIP, fonts ZIP or theme ZIP');box.appendChild(node('p','Maximum: 64 MiB uploaded, 32 MiB per media file, 256 KiB per text file, 128 MiB expanded and 500 ZIP entries. Invalid data is rejected before application.','hint'));upload(box,'settings');var exp=card(parent,'Export');['ini','zip','fonts','themes','log'].forEach(function(kind){button(exp,'Download '+kind,async function(){var q=new URLSearchParams({kind:kind,sections:Array.from(document.querySelectorAll('[data-section]:checked')).map(function(e){return e.dataset.section;}).join(',')});['fonts','pictures','sounds'].forEach(function(k){q.set(k,String(document.getElementById('carry-'+k).checked));});var response=await signedFetch('/export?'+q);if(!response.ok)throw new Error(await response.text());var blob=await response.blob(),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=kind==='ini'?'reteclock-settings.ini':'reteclock-'+kind+'.zip';a.click();setTimeout(function(){URL.revokeObjectURL(url);},30000);});});}
  function server(parent){var c=card(parent,'Web server account and listener');c.appendChild(node('p',state.status));var account={enabled:state.enabled,user:state.user,password:'',port:state.port};input(c,'Enabled',account.enabled,'checkbox',function(v){account.enabled=v;});input(c,'Administrator ID',account.user,'text',function(v){account.user=v;});input(c,'New password (blank keeps current)',account.password,'password',function(v){account.password=v;});input(c,'Port',account.port,'number',function(v){account.port=v;},1024,65535);button(c,'Save server/account',async function(){if(!account.enabled&&!confirm('Stop the web server? You will need the device to enable it again.'))return;var values={revision:state.revision,user:account.user,port:account.port,enabled:account.enabled};if(account.password){crypto.checkPassword(account.password);var salt=crypto.base64(crypto.random(16)),nonce=crypto.base64(crypto.random(24)),verifier=await crypto.derive(account.password,crypto.unbase64(salt),20000);values.salt=salt;values.nonce=nonce;values.maskedVerifier=crypto.base64(await crypto.mask(auth.key,account.user,salt,nonce,verifier));verifier.fill(0);account.password='';}message(await post('/account',values));if(auth)auth.key.fill(0);showLogin();message('Account saved. Reconnect and sign in again.');});}
  function sunTable(parent){var c=card(parent,'Next seven days · clock time'),scroll=node('div',undefined,'scroll'),t=node('table'),head=node('tr');['Day','Sunrise','Sunset','Noon','Dawn','Dusk','Night middle','Shadow','Evening'].forEach(function(n){head.appendChild(node('th',n));});t.appendChild(head);state.sunTable.forEach(function(r){var row=node('tr');row.appendChild(node('td',new Date(r.day*86400000).toISOString().slice(0,10)));r.times.forEach(function(m){row.appendChild(node('td',m<0?'—':('0'+Math.floor(m/60)).slice(-2)+':'+('0'+m%60).slice(-2)));});t.appendChild(row);});scroll.appendChild(t);c.appendChild(scroll);}
  function render(){mediaUrls.forEach(URL.revokeObjectURL);mediaUrls=[];var nav=document.getElementById('navigation'),content=document.getElementById('content');nav.replaceChildren();content.replaceChildren();Object.keys(titles).forEach(function(k){var b=button(nav,titles[k],function(){page=k;render();});if(k===page)b.className='selected';});content.appendChild(node('h2',titles[page]));if(page==='files'){files(content);return;}if(page==='server'){server(content);return;}
    if(page==='layouts'){layouts(content);}else {var general=card(content,'Settings');state.fields.filter(function(f){return f.page===page&&structured.indexOf(f.key)<0&&internal.indexOf(f.key)<0;}).forEach(function(f){valueField(general,f);});}
    if(page==='clock'){smallStructures(content);button(content,'Test spoken time on device',function(){return action('test-speech');});if(!state.voicesReady)content.appendChild(node('p','Discovering installed offline voices. Reload in a few seconds.','hint'));}
    if(page==='fonts'||page==='pictures')media(content,page);
    if(page==='pictures')button(content,'Open image trial on device',function(){return action('trial-images',{step:draft.image_quality});});
    if(page==='sounds'){var levels=card(content,'Test volume on device');['Ring','Vibrate','Silent'].forEach(function(mode,m){['Timer cues','Timer messages','Spoken time','Bells','Wake bells'].forEach(function(kind,k){button(levels,mode+' · '+kind,function(){return action('test-level',{mode:m,soundKind:k});});});});bells(content);clips(content);media(content,'sounds');sunTable(content);}
    if(page==='timer'){timers(content);button(content,'Delete timer log',function(){if(confirm('Delete all timer records?'))return action('clear-log');});}
    if(page==='timedate')dst(content);
    if(page==='experiments')content.appendChild(node('p','Wake alarms are experimental. Enabling them changes background alarm scheduling on the device; importing a settings file never enables this experiment.','warning'));
    var actions=node('div',undefined,'actions');content.appendChild(actions);button(actions,'Save changed settings',save);button(actions,'Discard changes and reload',load);button(actions,'Stop device test sound/speech',function(){return action('stop-test');});}
  document.getElementById('reload').onclick=function(){layoutMemory={};load().catch(function(e){message(e.message,true);});};showLogin();if(crypto&&window.crypto&&window.crypto.getRandomValues)document.getElementById('sign-in').disabled=false;else message('Secure browser cryptography unavailable',true);
})();
