package com.reteclock.core;

/**
 * The MABIMS Hijri calendar, baked.
 *
 * Generated by resources/prep/mabims.py — do not edit by hand.
 *
 * The reckoning Malaysia, Indonesia, Brunei and Singapore keep: on the evening of the 29th, at
 * sunset, the month ends if the crescent stands at least three degrees above the horizon and at
 * least 6.4 degrees from the sun. The criteria were agreed on 8 December 2021 and this table begins
 * where they took effect, in 1443 AH; before that the app has nothing to say and the Gregorian date
 * answers.
 *
 * Which reading of "where must the criterion be met" was not taken on faith. Three were computed —
 * anywhere in the territory, everywhere in it, and at a single reference point — and only
 * **everywhere** reproduces the authority's own dates. It was one marginal evening that decided it:
 * on 15 June 2026 the crescent cleared three degrees in the west of Malaysia and did not in the
 * east, and JAKIM waited.
 *
 * Verified before it was written: **twelve of twelve** consecutive month starts against JAKIM's own
 * published calendar for 2026, and **seven of seven** published new years from 1443 to 1449. The
 * one published date it does not match is 1450, which the holiday calendars themselves mark as
 * provisional.
 *
 * What it cannot do: Ramadan, Shawwal and Dhul-Hijjah are confirmed by sighting, and an
 * announcement can differ from the calculation by a day. This is the printed calendar, not the
 * announced one, and the app's -2..+2 day offset is the answer to the difference.
 *
 * Month lengths are twelve bits a year, the high bit first, a set bit meaning thirty days.
 * Years 1443 to 1626 AH.
 */
final class MabimsTable {

    /** The first year the table covers — where the criteria began. */
    static final int FIRST_YEAR = 1443;
    /** And the last. */
    static final int LAST_YEAR = 1626;

    /** The day 1 Muharram 1443 began on; the rest are offsets from it. */
    private static final int BASE_JDN = 2459437;

    private MabimsTable() {
    }

    private static final int[] MONTHS = {
        0x0556, 0x0AAA, 0x0D54, 0x0DB2, 0x05D9, 0x02DC, 0x095D, 0x04AE, 0x0A56, 0x0B2A, 0x0D55, 0x05AA,
        0x09B5, 0x04B7, 0x0257, 0x0527, 0x068D, 0x074A, 0x0B55, 0x035A, 0x0A9D, 0x052E, 0x0A96, 0x0D4A,
        0x0EA5, 0x06D2, 0x06D9, 0x055A, 0x0AAD, 0x054D, 0x0AA5, 0x0B52, 0x0BA9, 0x03B4, 0x09B6, 0x04D6,
        0x0957, 0x054B, 0x05A5, 0x05D4, 0x0ADA, 0x02ED, 0x026E, 0x092E, 0x0A96, 0x0D4B, 0x05A9, 0x05D5,
        0x02DA, 0x095B, 0x049B, 0x0A4B, 0x0AA5, 0x0B52, 0x0B65, 0x05AA, 0x0AAD, 0x0956, 0x0AA6, 0x0D8A,
        0x0EC5, 0x06D4, 0x0AEA, 0x056D, 0x02AD, 0x0955, 0x0B29, 0x0B64, 0x0BB2, 0x05B9, 0x02BA, 0x093B,
        0x04AB, 0x0555, 0x0AA9, 0x0AD5, 0x02EA, 0x096D, 0x04AE, 0x0957, 0x04A7, 0x0593, 0x06AA, 0x0AD5,
        0x04DA, 0x0A5B, 0x052B, 0x0A95, 0x0D49, 0x0DA4, 0x0DAA, 0x06B5, 0x04B6, 0x0A56, 0x0D2A, 0x0EA2,
        0x0ED1, 0x06E8, 0x0AF2, 0x0975, 0x04B6, 0x0A56, 0x0D52, 0x0DA9, 0x05D4, 0x0ADA, 0x04DD, 0x025D,
        0x052D, 0x0A95, 0x0B2A, 0x0B59, 0x056C, 0x0A76, 0x04B6, 0x0C57, 0x062B, 0x06A5, 0x06D2, 0x0B59,
        0x056D, 0x02AD, 0x0A4D, 0x0D25, 0x0D92, 0x0EA9, 0x05D4, 0x0ADA, 0x055A, 0x0AAB, 0x054B, 0x06A5,
        0x0754, 0x0769, 0x0374, 0x0ABA, 0x053A, 0x0AAA, 0x0D54, 0x0EAA, 0x06D4, 0x0ADC, 0x095D, 0x04AE,
        0x0A4E, 0x0B26, 0x0D55, 0x05AA, 0x05AD, 0x02B6, 0x0957, 0x0517, 0x068B, 0x0725, 0x0754, 0x0B6A,
        0x056D, 0x04AE, 0x0A96, 0x0D4A, 0x0E94, 0x0ED2, 0x06D5, 0x02EA, 0x096D, 0x04AD, 0x0A95, 0x0AC9,
        0x0B64, 0x0BB2, 0x05B6, 0x02B6, 0x0957, 0x052B, 0x0595, 0x06CA, 0x0AD9, 0x02ED, 0x016E, 0x04AE,
        0x0A97, 0x054B, 0x06A5, 0x06D2,
    };

    private static final int[] STARTS = {
        0, 354, 708, 1062, 1417, 1772, 2126, 2481, 2835, 3189, 3543, 3898,
        4252, 4607, 4962, 5316, 5670, 6024, 6378, 6733, 7087, 7442, 7796, 8150,
        8504, 8859, 9213, 9568, 9922, 10277, 10631, 10985, 11339, 11694, 12048, 12403,
        12757, 13112, 13466, 13820, 14174, 14529, 14884, 15238, 15592, 15946, 16301, 16655,
        17010, 17364, 17719, 18073, 18427, 18781, 19135, 19490, 19844, 20199, 20553, 20907,
        21261, 21616, 21970, 22325, 22680, 23034, 23388, 23742, 24096, 24451, 24806, 25160,
        25515, 25869, 26223, 26577, 26932, 27286, 27641, 27995, 28350, 28704, 29058, 29412,
        29767, 30121, 30476, 30830, 31184, 31538, 31892, 32247, 32602, 32956, 33310, 33664,
        34018, 34373, 34727, 35082, 35437, 35791, 36145, 36499, 36854, 37208, 37563, 37918,
        38272, 38626, 38980, 39334, 39689, 40043, 40398, 40752, 41107, 41461, 41815, 42169,
        42524, 42879, 43233, 43587, 43941, 44295, 44650, 45004, 45359, 45713, 46068, 46422,
        46776, 47130, 47485, 47839, 48194, 48548, 48902, 49256, 49611, 49965, 50320, 50675,
        51029, 51383, 51737, 52092, 52446, 52801, 53155, 53510, 53864, 54218, 54572, 54926,
        55281, 55636, 55990, 56344, 56698, 57052, 57407, 57762, 58116, 58471, 58825, 59179,
        59533, 59887, 60242, 60597, 60951, 61306, 61660, 62014, 62368, 62723, 63078, 63432,
        63786, 64141, 64495, 64849,
    };

    static boolean covers(int year) {
        return year >= FIRST_YEAR && year <= LAST_YEAR;
    }

    static int newYear(int year) {
        return STARTS[year - FIRST_YEAR] + BASE_JDN;
    }

    static int daysInMonth(int year, int month) {
        return (MONTHS[year - FIRST_YEAR] & (1 << (12 - month))) != 0 ? 30 : 29;
    }
}
