package com.reteclock.core;

/**
 * The Umm al-Qura calendar, baked.
 *
 * Generated by resources/prep/umalqura-table.py — do not edit by hand.
 *
 * This is the Hijri calendar Saudi Arabia keeps and much of the Gulf follows, and it is not the
 * tabular rule: it is calculated from the moon at Mecca, and it disagrees with the tabular rule
 * about which day a month starts on in more than a third of all months. Where the app has this
 * table it uses it; outside the years it covers, the tabular rule answers instead.
 *
 * Month lengths are twelve bits a year, a set bit meaning thirty days. Years 1300 to 1600 AH.
 *
 * Source: UMALQURA_MONTHLENGTH in ICU's icu4c/source/i18n/islamcal.cpp, © Unicode, Inc., used under
 * the Unicode licence, which permits redistribution with attribution. See
 * docs/resources/sources-and-licenses.md. The table was checked against the dates Saudi Arabia
 * announced for the new years of 1445, 1446 and 1447, for the first of Ramadan 1446, and for Eid
 * al-Fitr 1446 before it was written.
 */
final class UmalquraTable {

    /** The first year the table covers. */
    static final int FIRST_YEAR = 1300;
    /** And the last. */
    static final int LAST_YEAR = 1600;

    /** The day number 1 Muharram 1300 begins on; the rest are stored as offsets from it. */
    private static final int BASE_JDN = 2408762;

    private UmalquraTable() {
    }

    private static final int[] MONTHS = {
        0x0AAA, 0x0D54, 0x0EC9, 0x06D4, 0x06EA, 0x036C, 0x0AAD, 0x0555, 0x06A9, 0x0792, 0x0BA9, 0x05D4,
        0x0ADA, 0x055C, 0x0D2D, 0x0695, 0x074A, 0x0B54, 0x0B6A, 0x05AD, 0x04AE, 0x0A4F, 0x0517, 0x068B,
        0x06A5, 0x0AD5, 0x02D6, 0x095B, 0x049D, 0x0A4D, 0x0D26, 0x0D95, 0x05AC, 0x09B6, 0x02BA, 0x0A5B,
        0x052B, 0x0A95, 0x06CA, 0x0AE9, 0x02F4, 0x0976, 0x02B6, 0x0956, 0x0ACA, 0x0BA4, 0x0BD2, 0x05D9,
        0x02DC, 0x096D, 0x054D, 0x0AA5, 0x0B52, 0x0BA5, 0x05B4, 0x09B6, 0x0557, 0x0297, 0x054B, 0x06A3,
        0x0752, 0x0B65, 0x056A, 0x0AAB, 0x052B, 0x0C95, 0x0D4A, 0x0DA5, 0x05CA, 0x0AD6, 0x0957, 0x04AB,
        0x094B, 0x0AA5, 0x0B52, 0x0B6A, 0x0575, 0x0276, 0x08B7, 0x045B, 0x0555, 0x05A9, 0x05B4, 0x09DA,
        0x04DD, 0x026E, 0x0936, 0x0AAA, 0x0D54, 0x0DB2, 0x05D5, 0x02DA, 0x095B, 0x04AB, 0x0A55, 0x0B49,
        0x0B64, 0x0B71, 0x05B4, 0x0AB5, 0x0A55, 0x0D25, 0x0E92, 0x0EC9, 0x06D4, 0x0AE9, 0x096B, 0x04AB,
        0x0A93, 0x0D49, 0x0DA4, 0x0DB2, 0x0AB9, 0x04BA, 0x0A5B, 0x052B, 0x0A95, 0x0B2A, 0x0B55, 0x055C,
        0x04BD, 0x023D, 0x091D, 0x0A95, 0x0B4A, 0x0B5A, 0x056D, 0x02B6, 0x093B, 0x049B, 0x0655, 0x06A9,
        0x0754, 0x0B6A, 0x056C, 0x0AAD, 0x0555, 0x0B29, 0x0B92, 0x0BA9, 0x05D4, 0x0ADA, 0x055A, 0x0AAB,
        0x0595, 0x0749, 0x0764, 0x0BAA, 0x05B5, 0x02B6, 0x0A56, 0x0E4D, 0x0B25, 0x0B52, 0x0B6A, 0x05AD,
        0x02AE, 0x092F, 0x0497, 0x064B, 0x06A5, 0x06AC, 0x0AD6, 0x055D, 0x049D, 0x0A4D, 0x0D16, 0x0D95,
        0x05AA, 0x05B5, 0x02DA, 0x095B, 0x04AD, 0x0595, 0x06CA, 0x06E4, 0x0AEA, 0x04F5, 0x02B6, 0x0956,
        0x0AAA, 0x0B54, 0x0BD2, 0x05D9, 0x02EA, 0x096D, 0x04AD, 0x0A95, 0x0B4A, 0x0BA5, 0x05B2, 0x09B5,
        0x04D6, 0x0A97, 0x0547, 0x0693, 0x0749, 0x0B55, 0x056A, 0x0A6B, 0x052B, 0x0A8B, 0x0D46, 0x0DA3,
        0x05CA, 0x0AD6, 0x04DB, 0x026B, 0x094B, 0x0AA5, 0x0B52, 0x0B69, 0x0575, 0x0176, 0x08B7, 0x025B,
        0x052B, 0x0565, 0x05B4, 0x09DA, 0x04ED, 0x016D, 0x08B6, 0x0AA6, 0x0D52, 0x0DA9, 0x05D4, 0x0ADA,
        0x095B, 0x04AB, 0x0653, 0x0729, 0x0762, 0x0BA9, 0x05B2, 0x0AB5, 0x0555, 0x0B25, 0x0D92, 0x0EC9,
        0x06D2, 0x0AE9, 0x056B, 0x04AB, 0x0A55, 0x0D29, 0x0D54, 0x0DAA, 0x09B5, 0x04BA, 0x0A3B, 0x049B,
        0x0A4D, 0x0AAA, 0x0AD5, 0x02DA, 0x095D, 0x045E, 0x0A2E, 0x0C9A, 0x0D55, 0x06B2, 0x06B9, 0x04BA,
        0x0A5D, 0x052D, 0x0A95, 0x0B52, 0x0BA8, 0x0BB4, 0x05B9, 0x02DA, 0x095A, 0x0B4A, 0x0DA4, 0x0ED1,
        0x06E8, 0x0B6A, 0x056D, 0x0535, 0x0695, 0x0D4A, 0x0DA8, 0x0DD4, 0x06DA, 0x055B, 0x029D, 0x062B,
        0x0B15, 0x0B4A, 0x0B95, 0x05AA, 0x0AAE, 0x092E, 0x0C8F, 0x0527, 0x0695, 0x06AA, 0x0AD6, 0x055D,
        0x029D,
    };

    private static final int[] STARTS = {
        0, 354, 708, 1063, 1417, 1772, 2126, 2481, 2835, 3189, 3543, 3898,
        4252, 4607, 4961, 5316, 5670, 6024, 6378, 6733, 7088, 7442, 7797, 8151,
        8505, 8859, 9214, 9568, 9923, 10277, 10631, 10985, 11340, 11694, 12049, 12403,
        12758, 13112, 13466, 13820, 14175, 14529, 14884, 15238, 15592, 15946, 16300, 16655,
        17010, 17364, 17719, 18073, 18427, 18781, 19136, 19490, 19845, 20200, 20554, 20908,
        21262, 21616, 21971, 22325, 22680, 23034, 23388, 23742, 24097, 24451, 24806, 25161,
        25515, 25869, 26223, 26577, 26932, 27287, 27641, 27996, 28350, 28704, 29058, 29412,
        29767, 30122, 30476, 30830, 31184, 31538, 31893, 32248, 32602, 32957, 33311, 33665,
        34019, 34373, 34728, 35082, 35437, 35791, 36145, 36499, 36854, 37208, 37563, 37918,
        38272, 38626, 38980, 39334, 39689, 40044, 40398, 40753, 41107, 41461, 41815, 42170,
        42524, 42879, 43233, 43587, 43941, 44295, 44650, 45005, 45359, 45714, 46068, 46422,
        46776, 47130, 47485, 47839, 48194, 48548, 48902, 49256, 49611, 49965, 50320, 50674,
        51029, 51383, 51737, 52091, 52446, 52801, 53155, 53509, 53864, 54218, 54572, 54927,
        55282, 55636, 55991, 56345, 56699, 57053, 57407, 57762, 58117, 58471, 58825, 59179,
        59534, 59888, 60243, 60597, 60952, 61306, 61660, 62014, 62368, 62723, 63078, 63432,
        63786, 64140, 64494, 64849, 65204, 65558, 65913, 66267, 66621, 66975, 67330, 67684,
        68039, 68393, 68748, 69102, 69456, 69810, 70165, 70519, 70874, 71228, 71582, 71936,
        72291, 72645, 73000, 73355, 73709, 74063, 74417, 74771, 75126, 75481, 75835, 76190,
        76544, 76898, 77252, 77606, 77961, 78316, 78670, 79024, 79378, 79732, 80087, 80441,
        80796, 81151, 81505, 81859, 82213, 82567, 82922, 83276, 83631, 83985, 84339, 84693,
        85048, 85402, 85757, 86112, 86466, 86820, 87174, 87528, 87883, 88238, 88592, 88947,
        89301, 89655, 90009, 90364, 90718, 91073, 91427, 91781, 92135, 92490, 92844, 93199,
        93553, 93908, 94262, 94616, 94970, 95324, 95679, 96034, 96388, 96742, 97096, 97450,
        97805, 98159, 98514, 98869, 99223, 99577, 99931, 100285, 100640, 100995, 101350, 101704,
        102058, 102412, 102766, 103121, 103475, 103830, 104184, 104539, 104893, 105247, 105601, 105956,
        106311,
    };

    /** Whether the table can answer for a year at all. */
    static boolean covers(int year) {
        return year >= FIRST_YEAR && year <= LAST_YEAR;
    }

    /** The day number 1 Muharram of that year begins on. */
    static int newYear(int year) {
        return STARTS[year - FIRST_YEAR] + BASE_JDN;
    }

    /** Twenty-nine days, or thirty. The first month is the high bit; see the generator. */
    static int daysInMonth(int year, int month) {
        return (MONTHS[year - FIRST_YEAR] & (1 << (12 - month))) != 0 ? 30 : 29;
    }
}
